Homepage:
    pattern:  /
    defaults: { _controller: "Application:Index:index"}

Create_Module:
    pattern:  /module/create
    defaults: { _controller: "Application:Module:create"}

Lookup_Packagist:
    pattern:  /module/packagist/lookup
    defaults: { _controller: "Application:Module:lookupPackagist"}

Module_Screenshot_Upload:
    pattern:  /module/screenshot/upload
    defaults: { _controller: "Application:Module:uploadScreenshot"}

Module_Save:
    pattern:  /module/save
    defaults: { _controller: "Application:Module:save"}

Module_Set_Description:
    pattern:  /module/description/set
    defaults: { _controller: "Application:Module:setDesc"}

Module_Finish:
    pattern:  /module/finish
    defaults: { _controller: "Application:Module:finish"}

Module_View:
    pattern:  /module/view/{moduleID}
    defaults: { _controller: "Application:Module:view"}